import mysql.connector
import pandas as pd
from fpdf import FPDF
import schedule
import time
from datetime import datetime

# ─────────────────────────────────────────
# 1. CONNECT TO MYSQL & FETCH DATA
# ─────────────────────────────────────────
def fetch_sales_data():
    conn = mysql.connector.connect(
        host="localhost",
        user="root",           # change if different
        password="yourpassword",  # 🔁 change to your MySQL password
        database="sales_db"
    )
    query = "SELECT * FROM sales"
    df = pd.read_sql(query, conn)
    conn.close()
    return df


# ─────────────────────────────────────────
# 2. ANALYZE DATA
# ─────────────────────────────────────────
def analyze_data(df):
    summary = {
        "total_sales": df["amount"].sum(),
        "total_orders": len(df),
        "avg_order_value": df["amount"].mean(),
        "top_product": df.groupby("product")["amount"].sum().idxmax(),
        "top_region": df.groupby("region")["amount"].sum().idxmax(),
        "product_summary": df.groupby("product")["amount"].sum().reset_index(),
        "region_summary": df.groupby("region")["amount"].sum().reset_index(),
    }
    return summary


# ─────────────────────────────────────────
# 3. GENERATE PDF REPORT
# ─────────────────────────────────────────
def generate_pdf(summary):
    pdf = FPDF()
    pdf.add_page()

    # ── Title ──
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_fill_color(30, 30, 80)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 14, "Sales Performance Report", ln=True, align="C", fill=True)

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 8, f"Generated on: {datetime.now().strftime('%d %B %Y, %I:%M %p')}", ln=True, align="C")
    pdf.ln(6)

    # ── Key Metrics ──
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_fill_color(220, 230, 255)
    pdf.cell(0, 10, "  Key Metrics", ln=True, fill=True)
    pdf.ln(3)

    pdf.set_font("Helvetica", "", 11)
    metrics = [
        ("Total Revenue", f"Rs. {summary['total_sales']:,.2f}"),
        ("Total Orders", str(summary["total_orders"])),
        ("Avg Order Value", f"Rs. {summary['avg_order_value']:,.2f}"),
        ("Top Product", summary["top_product"]),
        ("Top Region", summary["top_region"]),
    ]
    for label, value in metrics:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(70, 9, f"  {label}:", border=0)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 9, value, ln=True)
    pdf.ln(6)

    # ── Product Summary Table ──
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_fill_color(220, 230, 255)
    pdf.cell(0, 10, "  Sales by Product", ln=True, fill=True)
    pdf.ln(3)

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(200, 210, 240)
    pdf.cell(95, 9, "  Product", border=1, fill=True)
    pdf.cell(95, 9, "  Total Sales (Rs.)", border=1, fill=True, ln=True)

    pdf.set_font("Helvetica", "", 11)
    for _, row in summary["product_summary"].iterrows():
        pdf.cell(95, 9, f"  {row['product']}", border=1)
        pdf.cell(95, 9, f"  {row['amount']:,.2f}", border=1, ln=True)
    pdf.ln(6)

    # ── Region Summary Table ──
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_fill_color(220, 230, 255)
    pdf.cell(0, 10, "  Sales by Region", ln=True, fill=True)
    pdf.ln(3)

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(200, 210, 240)
    pdf.cell(95, 9, "  Region", border=1, fill=True)
    pdf.cell(95, 9, "  Total Sales (Rs.)", border=1, fill=True, ln=True)

    pdf.set_font("Helvetica", "", 11)
    for _, row in summary["region_summary"].iterrows():
        pdf.cell(95, 9, f"  {row['region']}", border=1)
        pdf.cell(95, 9, f"  {row['amount']:,.2f}", border=1, ln=True)
    pdf.ln(8)

    # ── Footer ──
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 8, "Auto-generated by Sales Report Generator | Thanisha M Shetty", align="C")

    # Save PDF
    filename = f"sales_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    pdf.output(filename)
    print(f"✅ Report generated: {filename}")


# ─────────────────────────────────────────
# 4. MAIN JOB FUNCTION
# ─────────────────────────────────────────
def generate_report():
    print(f"\n⏳ Running report at {datetime.now().strftime('%I:%M %p')}...")
    df = fetch_sales_data()
    summary = analyze_data(df)
    generate_pdf(summary)


# ─────────────────────────────────────────
# 5. SCHEDULER — runs every day at 9 AM
# ─────────────────────────────────────────
if __name__ == "__main__":
    print("🚀 Sales Report Generator Started!")
    print("📅 Scheduled to run every day at 9:00 AM")
    print("▶  Running once now for testing...\n")

    generate_report()  # Run once immediately for testing

    schedule.every().day.at("09:00").do(generate_report)

    while True:
        schedule.run_pending()
        time.sleep(60)